import { cookies } from "next/headers"

const DB_URL = "https://cuerosportenos-35545-default-rtdb.firebaseio.com"

async function getAuthToken(): Promise<string | null> {
    try {
        const cookieStore = await cookies()
        return cookieStore.get("firebase-token")?.value || null
    } catch {
        return null
    }
}

export async function serverDbSet(path: string, data: any) {
    const token = await getAuthToken()
    const url = `${DB_URL}/${path}.json${token ? `?auth=${token}` : ""}`
    
    const res = await fetch(url, {
        method: "PUT",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(data)
    })

    if (!res.ok) {
        const errText = await res.text()
        throw new Error(`Database write failed (PUT): ${errText}`)
    }

    return res.json()
}

export async function serverDbUpdate(path: string, data: any) {
    const token = await getAuthToken()
    const url = `${DB_URL}/${path}.json${token ? `?auth=${token}` : ""}`
    
    const res = await fetch(url, {
        method: "PATCH",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(data)
    })

    if (!res.ok) {
        const errText = await res.text()
        throw new Error(`Database write failed (PATCH): ${errText}`)
    }

    return res.json()
}

export async function serverDbPush(path: string, data: any) {
    const token = await getAuthToken()
    const url = `${DB_URL}/${path}.json${token ? `?auth=${token}` : ""}`
    
    const res = await fetch(url, {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(data)
    })

    if (!res.ok) {
        const errText = await res.text()
        throw new Error(`Database write failed (POST): ${errText}`)
    }

    const result = await res.json()
    return result.name as string // Returns the autogenerated key (e.g. "-OKjsa...")
}
